vending:
  model:
    # Default model name for the simulation (can be overridden in the UI)
    name: "gemini-1.5-flash"
    # The environment variable that holds the API key for the selected provider
    api-env-var: "GOOGLE_API_KEY"